### ISSUE TITLE
Missing documentation for `btShapes`

### ISSUE THREAD

**Issue by kaijagahm** [aaronolsen/StereoMorph#11]
Hi there,
Thanks for making this package! It has been really helpful for a morphometric analysis that I'm helping with.

I noticed that documentation for the `btShapes` function isn't included in the R manual, and `help(btShapes)` doesn't turn up any documentation for that function. In my case, this is making it hard to understand my collaborator's code, and hard to document my own code to make sure what I'm doing will be reproducible by someone who knows very little about the package.

Would you consider adding a .Rd documentation file to the man/ folder and the R manual?

Thank you!

**Comment by aaronolsen** [comment]
HI Kaija,

Thanks for your message! Due to personal reasons I'm not currently doing any development/documentation work on StereoMorph, other than the most urgent fixes (e.g. necessary to maintain the package on CRAN). I'm hoping to resume work on it at some point in the future but I can't provide a definite date at this time. While this function in particular isn't documented, I've written a tutorial here: https://aaronolsen.github.io/tutorials/morphometrics/backtransform.html.

Thank you for your understanding,
Aaron

**Comment by kaijagahm** [comment]
Sure, I understand. Thanks for pointing me to the tutorial! It looks helpful.
