### ISSUE TITLE
NaN landmark values in digitizeImages Shiny app when reading saved shape file

### ISSUE THREAD

**Issue by Entomophagist** [aaronolsen/StereoMorph#13]
**Description**
As of the latest update to the package, the Shiny app called by the digitizeImages function fails to read landmark and curve values from the shape files it creates. It still _creates_ shape files without issue and reads the tutorial shape files without issue.

**My system**
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit) (Ubuntu 20.04.4 LTS)
StereoMorph version: 1.6.5 (built under R 4.2.0)

**Steps to reproduce**
1. Download the Mug Project zip from [the StereoMorph site](https://aaronolsen.github.io/software/stereomorph.html)
2. Extract, create a new RStudio session in .../Mug project/Mug project/
3. Run digitizeImages with: `digitizeImages(image.file='Mugs', shapes.file='Shapes',
              landmarks.ref='landmarks.txt')
`
Here you can see that the app _reads_ the included shape data just fine.
![image](https://user-images.githubusercontent.com/95774269/170084974-c80ba75d-a8b5-4d91-89d0-67f8325a3224.png)
4. Assign a new point to Handle_Cup_Out_Top (or any landmark). The new value is assigned without problem.
![image](https://user-images.githubusercontent.com/95774269/170085274-522c2b6e-954e-4a5b-82b5-3dadc7bd104a.png)
5. Save the shape file. No sign of error.
6. Advance to the next image and then return to mug_001.jpg. All landmark values will have changed to NaN and will not display on the image.
![image](https://user-images.githubusercontent.com/95774269/170085557-067eed6e-3deb-4372-a7da-d55174887b85.png)

Original shape file contents:
![image](https://user-images.githubusercontent.com/95774269/170086441-55523538-98ea-4a40-aa3e-e05b24514f52.png)

Contents of shape file saved on Step 5:
![image](https://user-images.githubusercontent.com/95774269/170086521-bdb44e6c-1d37-4176-8ea3-21b1d6916f3a.png)

**Speculation**
It seems the error was created when the package was updated so that digitizeImages saves the shape file in a new format but it hasn't been updated to read that new format. It expects the old format and so it throws NaN values when opening a new-format file.

**Comment by aaronolsen** [comment]
Thank you @Entomophagist! This is definitely a bug. I was alerted to it earlier this morning by another user. I'm currently fixing it. I'll hopefully have a fix by later today.

**Comment by aaronolsen** [comment]
I think I have fixed the error. An update in StereoMorph v1.6.5 caused the shape file writing function to insert extra lines such as the following:

<landmarks.pixel type=array dim=22,2 as.numeric=TRUE >

This because the structure was recognized twice as a matrix and an array. I've fixed the error that causes this additional line to be written in the shapes files.

I've also added a check to the XML4R2listLines function to ignore these erroneously added lines.

So if you have any shapes files with these lines they can still be read without an issue and once you save them again the extra line will be removed. I'll send a new version to CRAN once I do a few more tests.
