### ISSUE TITLE
Submit landmarks?

### ISSUE THREAD

**Issue by tommydevitt** [aaronolsen/StereoMorph#6]
I'm trying to work through the tutorial and am not seeing a "Submit all" or "Submit landmarks" button in the bottom right corner of the control panel as is shown on page 10 of the tutorial. Am I missing something? When I save the landmarks, I get 

Warning in if (class(list[[name]]) == "array") { :
  the condition has length > 1 and only the first element will be used

Thanks for your help.

**Comment by aaronolsen** [comment]
Hi @tommydevitt! Thanks for posting your question. That's just because that tutorial is out of date relative to the current version of StereoMorph on CRAN. Please use the tutorial posted here: https://aaronolsen.github.io/tutorials/stereomorph.html. In the "Digitizing photographs" section (https://aaronolsen.github.io/tutorials/stereomorph/digitizing_photographs.html) you'll see the "Submit all" and "Submit landmarks" have been simplified to a simple "Save" button. I apologize for any confusion!

Aaron

**Comment by tommydevitt** [comment]
Thanks for your prompt reply, @aaronolsen.
